spring:
  application:
    name: my.zuul
    
  jmx:
    enabled: false
    
#server:
#  port: 8080
  
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8080/my.demo/eureka/
  instance: 
    lease-renewal-interval-in-seconds: 50
    lease-expiration-duration-in-seconds: 30
      
hystrix:  
  command:  
      default:  
        execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 9000 
              
zuul:
  add-host-header: true
  routes:
    kkk: 
      path: /my.web/**
      service-id: my.web
feign:
 httpclient:
    time-to-live: 5000
     
              
ribbon: 
  ConnectTimeout: 10000
  ReadTimeout: 6000